version: '3.7'

services:
  app:    
    container_name: nestjs    
    build:
      context: .      
      dockerfile: 'Dockerfile'      
    command: bash -c "npm run start:dev"
    ports:
      - 8080:8080
    networks:
      - nestjs-network        
    env_file:
      - .env
    working_dir: /usr/src/app          
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_USERNAME: ${MONGO_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27027:27017
    networks:
      - nestjs-network
networks:
  nestjs-network:
    driver: bridge     
